// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKBvN03N6dogb65KTcF2Rlb7vOvPfNoak',
    appId: '1:84733806651:web:57579eb27209fc35ba741e',
    messagingSenderId: '84733806651',
    projectId: 'musaed-dev',
    authDomain: 'musaed-dev.firebaseapp.com',
    storageBucket: 'musaed-dev.firebasestorage.app',
    measurementId: 'G-RQLGHG3SBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYYJaiiXBkHPo_8C23Mfb_-iNlsme4mmo',
    appId: '1:84733806651:android:c1842cc3dc6dfca5ba741e',
    messagingSenderId: '84733806651',
    projectId: 'musaed-dev',
    storageBucket: 'musaed-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1fj5n0wXR-sOVs5Shdb7lCKtc7S0qB-s',
    appId: '1:84733806651:ios:c38e23c078ce6fe6ba741e',
    messagingSenderId: '84733806651',
    projectId: 'musaed-dev',
    storageBucket: 'musaed-dev.firebasestorage.app',
    iosBundleId: 'com.app.musaeidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1fj5n0wXR-sOVs5Shdb7lCKtc7S0qB-s',
    appId: '1:84733806651:ios:c38e23c078ce6fe6ba741e',
    messagingSenderId: '84733806651',
    projectId: 'musaed-dev',
    storageBucket: 'musaed-dev.firebasestorage.app',
    iosBundleId: 'com.app.musaeidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKBvN03N6dogb65KTcF2Rlb7vOvPfNoak',
    appId: '1:84733806651:web:adbb46aeeb45f794ba741e',
    messagingSenderId: '84733806651',
    projectId: 'musaed-dev',
    authDomain: 'musaed-dev.firebaseapp.com',
    storageBucket: 'musaed-dev.firebasestorage.app',
    measurementId: 'G-LK9JW4KL37',
  );
}
