// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlVkYOpySTeemrKm55ywbK3pz-GJj6qRM',
    appId: '1:784984253888:web:36486689b4016890de9425',
    messagingSenderId: '784984253888',
    projectId: 'ager-wafer',
    authDomain: 'ager-wafer.firebaseapp.com',
    storageBucket: 'ager-wafer.firebasestorage.app',
    measurementId: 'G-GQX4NM6YDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpf3ycfO4IonCYfLg_-5De8zfPAJJ3n2Q',
    appId: '1:784984253888:android:8affe7b0d07eda68de9425',
    messagingSenderId: '784984253888',
    projectId: 'ager-wafer',
    storageBucket: 'ager-wafer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOI2J2wfILgwsgbjhvsYt8yzS9zQr475I',
    appId: '1:784984253888:ios:973093a9715902bfde9425',
    messagingSenderId: '784984253888',
    projectId: 'ager-wafer',
    storageBucket: 'ager-wafer.firebasestorage.app',
    iosBundleId: 'com.example.agerWaffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOI2J2wfILgwsgbjhvsYt8yzS9zQr475I',
    appId: '1:784984253888:ios:973093a9715902bfde9425',
    messagingSenderId: '784984253888',
    projectId: 'ager-wafer',
    storageBucket: 'ager-wafer.firebasestorage.app',
    iosBundleId: 'com.example.agerWaffer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlVkYOpySTeemrKm55ywbK3pz-GJj6qRM',
    appId: '1:784984253888:web:553c4d913c142ee9de9425',
    messagingSenderId: '784984253888',
    projectId: 'ager-wafer',
    authDomain: 'ager-wafer.firebaseapp.com',
    storageBucket: 'ager-wafer.firebasestorage.app',
    measurementId: 'G-K6WYP2J5Z2',
  );
}
